### ISSUE TITLE
Release page differed than Github

### ISSUE THREAD

**Issue by pydubreucq** [haraka/haraka.github.io#19]
Hi,
Just to inform you that the Release page on Haraka Docs don't have the last Haraka Version
https://haraka.github.io/releases/
vs
https://github.com/haraka/Haraka/releases

I searched for a way to update this page, but I couldn't find it :( sorry

Best Regards,
Pierre-Yves

**Comment by sent** [comment]
Hello,

I will take care of it. Sorry about that as I waiting for the new release of docus!

Thanks!
