### ISSUE TITLE
All internal pages give a 404 error

### ISSUE THREAD

**Issue by lobovkin** [haraka/haraka.github.io#34]
Hello.
It started a few days ago, only the main page works https://haraka.github.io/
All internal with error 404: https://haraka.github.io/getting_started

**Comment by msimerson** [comment]
Hey @sent, do you know why this is happening?

**Comment by sent** [comment]
Hello,

Looks like pages weren't build at all, related issue https://github.com/nuxt-themes/docus/issues/799.

I'll push a new commit to pin the version.

Thanks!
